In [1]:
import pandas as pd
import numpy as np
import requests
import warnings
from dotenv import load_dotenv
from datetime import datetime
import os
import json
from pandas.errors import SettingWithCopyWarning

load_dotenv()
warnings.simplefilter("ignore", SettingWithCopyWarning)

In [2]:
landslides = pd.read_excel("../Datasets/Colombia Lansdslides Table.xlsx")

display(landslides.info())
landslides

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2266 entries, 0 to 2265
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Occurrence Date        2266 non-null   datetime64[ns]
 1   Department             2266 non-null   object
 2   Municipality           2266 non-null   object
 3   Lat                    2266 non-null   object
 4   Long                   2266 non-null   object
 5   Confidence ratio (km)  2266 non-null   object
 6   Deaths                 2266 non-null   int64
 7   Trigger                2266 non-null   object
 8   Source                 2266 non-null   object
dtypes: datetime64[ns](1), int64(1), object(7)
memory usage: 159.5+ KB

None

,Occurrence Date,Department,Municipality,Lat,Long,Confidence ratio (km),Deaths,Trigger,Source
0,1934-05-30,ANTIOQUIA,ABRIAQUI,6.63,-76.09,9.65,5,Rainfall,CNMM
1,1934-09-29,BOGOTA,BOGOTA,4.63,-74.11,11.6,2,Human activity,HEB
2,1934-11-18,CALDAS,CHINCHINA,4.97,-75.66,5.92,1,Unknown,CNMM
3,1934-11-28,VALLE DEL CAUCA,CALI,3.4,-76.58,13.44,2,Unknown,CNMM
4,1934-11-29,QUINDIO,ARMENIA,4.5,-75.73,6.17,1,Unknown,DESINVENTAR
...,...,...,...,...,...,...,...,...,...
2261,2020-12-01,BOLIVAR,BARRANCO DE LOBA,8.84,-74.28,11.68,3,Human activity,News Report - UNGRD
2262,2020-12-03,RISARALDA,PEREIRA,4.8,-75.8,13.91,1,Unknown,UNGRD
2263,2020-12-12,ANTIOQUIA,SAN LUIS,6,-75.05,0.1,2,Unknown,News Report
2264,2020-12-15,ANTIOQUIA,MEDELLIN,6.25,-75.58,6.5,2,Human activity,News Report
2265,2020-12-25,ANTIOQUIA,ITAGUI,6.18,-75.61,2.53,2,Earthquake,News Report - UNGRD

In [3]:
landslides.sort_values(["Lat", "Long"])

,Occurrence Date,Department,Municipality,Lat,Long,Confidence ratio (km),Deaths,Trigger,Source
641,1972-07-26,PUTUMAYO,PUERTO ASIS,0.43,-76.52,29.96,4,Unknown,CTM96 - DESINVENTAR
338,1962-08-16,NARIÃ‘O,IPIALES,0.5,-77.24,22.45,14,Unknown,CNMM
1125,1988-04-22,NARIÃ‘O,IPIALES,0.5,-77.24,22.45,29,Unknown,CNMM
1165,1988-12-03,NARIÃ‘O,IPIALES,0.5,-77.24,22.45,15,Rainfall,DESINVENTAR
1284,1994-08-03,NARIÃ‘O,IPIALES,0.5,-77.24,22.45,2,Unknown,DESINVENTAR
...,...,...,...,...,...,...,...,...,...
1445,2000-04-19,NARIÃ‘O,UNKNOWN,-,-,-,1,Rainfall,DESINVENTAR
1454,2000-07-02,ANTIOQUIA,UNKNOWN,-,-,-,1,Rainfall,DESINVENTAR
1455,2000-08-18,NARIÃ‘O,UNKNOWN,-,-,-,9,Human activity,DESINVENTAR
1513,2004-03-05,CUNDINAMARCA,UNKNOWN,-,-,-,1,Rainfall,DESINVENTAR
1749,2009-05-25,CHOCO,LITORAL DEL SAN JUAN,-,-,-,1,Unknown,UNGRD

In [4]:
landslides = landslides[landslides["Lat"] != "-"]
landslides[["Lat", "Long", "Confidence ratio (km)"]] = landslides[["Lat", "Long", "Confidence ratio (km)"]].astype(float)

display(landslides.info())
landslides

<class 'pandas.core.frame.DataFrame'>
Index: 2240 entries, 0 to 2265
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Occurrence Date        2240 non-null   datetime64[ns]
 1   Department             2240 non-null   object
 2   Municipality           2240 non-null   object
 3   Lat                    2240 non-null   float64
 4   Long                   2240 non-null   float64
 5   Confidence ratio (km)  2240 non-null   float64
 6   Deaths                 2240 non-null   int64
 7   Trigger                2240 non-null   object
 8   Source                 2240 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 175.0+ KB

None

,Occurrence Date,Department,Municipality,Lat,Long,Confidence ratio (km),Deaths,Trigger,Source
0,1934-05-30,ANTIOQUIA,ABRIAQUI,6.63,-76.09,9.65,5,Rainfall,CNMM
1,1934-09-29,BOGOTA,BOGOTA,4.63,-74.11,11.60,2,Human activity,HEB
2,1934-11-18,CALDAS,CHINCHINA,4.97,-75.66,5.92,1,Unknown,CNMM
3,1934-11-28,VALLE DEL CAUCA,CALI,3.40,-76.58,13.44,2,Unknown,CNMM
4,1934-11-29,QUINDIO,ARMENIA,4.50,-75.73,6.17,1,Unknown,DESINVENTAR
...,...,...,...,...,...,...,...,...,...
2261,2020-12-01,BOLIVAR,BARRANCO DE LOBA,8.84,-74.28,11.68,3,Human activity,News Report - UNGRD
2262,2020-12-03,RISARALDA,PEREIRA,4.80,-75.80,13.91,1,Unknown,UNGRD
2263,2020-12-12,ANTIOQUIA,SAN LUIS,6.00,-75.05,0.10,2,Unknown,News Report
2264,2020-12-15,ANTIOQUIA,MEDELLIN,6.25,-75.58,6.50,2,Human activity,News Report
2265,2020-12-25,ANTIOQUIA,ITAGUI,6.18,-75.61,2.53,2,Earthquake,News Report - UNGRD

In [5]:
landslides.describe()

,Occurrence Date,Lat,Long,Confidence ratio (km),Deaths
count,2240,2240.000000,2240.000000,2240.000000,2240.000000
mean,1987-08-02 23:06:38.571428480,5.118714,-75.272795,10.713237,16.127679
min,1934-05-30 00:00:00,0.430000,-78.600000,0.100000,1.000000
25%,1971-04-20 18:00:00,4.410000,-75.860000,6.170000,1.000000
50%,1988-09-17 00:00:00,5.070000,-75.510000,9.460000,2.000000
75%,2008-11-03 18:00:00,6.260000,-74.947500,13.430000,4.000000
max,2020-12-25 00:00:00,12.000000,75.750000,74.660000,21697.000000
std,NaN,1.890475,3.391700,7.528650,460.265346

In [6]:
landslides["Long"] = landslides["Long"].apply(lambda x: x if x <= 0 else -1 * x)

landslides.describe()

,Occurrence Date,Lat,Long,Confidence ratio (km),Deaths
count,2240,2240.000000,2240.000000,2240.000000,2240.000000
mean,1987-08-02 23:06:38.571428480,5.118714,-75.340429,10.713237,16.127679
min,1934-05-30 00:00:00,0.430000,-78.600000,0.100000,1.000000
25%,1971-04-20 18:00:00,4.410000,-75.860000,6.170000,1.000000
50%,1988-09-17 00:00:00,5.070000,-75.510000,9.460000,2.000000
75%,2008-11-03 18:00:00,6.260000,-74.950000,13.430000,4.000000
max,2020-12-25 00:00:00,12.000000,-68.010000,74.660000,21697.000000
std,NaN,1.890475,1.145650,7.528650,460.265346

In [7]:
landslides_recent = landslides[landslides["Occurrence Date"].dt.year >= 2010].reset_index(drop = True)

landslides_recent

,Occurrence Date,Department,Municipality,Lat,Long,Confidence ratio (km),Deaths,Trigger,Source
0,2010-01-10,BOGOTA,BOGOTA,4.63,-74.11,11.60,1,Unknown,HEB
1,2010-02-25,CUNDINAMARCA,VILLETA,5.01,-74.49,6.70,1,Rainfall,UNGRD
2,2010-04-10,TOLIMA,HERVEO,5.11,-75.19,1.52,1,Unknown,UNGRD
3,2010-04-10,VALLE DEL CAUCA,CALI,3.40,-76.58,13.44,1,Unknown,UNGRD
4,2010-04-29,BOGOTA,BOGOTA,4.63,-74.11,11.60,1,Unknown,UNGRD
...,...,...,...,...,...,...,...,...,...
499,2020-12-01,BOLIVAR,BARRANCO DE LOBA,8.84,-74.28,11.68,3,Human activity,News Report - UNGRD
500,2020-12-03,RISARALDA,PEREIRA,4.80,-75.80,13.91,1,Unknown,UNGRD
501,2020-12-12,ANTIOQUIA,SAN LUIS,6.00,-75.05,0.10,2,Unknown,News Report
502,2020-12-15,ANTIOQUIA,MEDELLIN,6.25,-75.58,6.50,2,Human activity,News Report
503,2020-12-25,ANTIOQUIA,ITAGUI,6.18,-75.61,2.53,2,Earthquake,News Report - UNGRD

In [8]:
rain_yesterday = []
rain_today = []

for i, row in landslides_recent.iterrows():
    start_date = (row["Occurrence Date"] + pd.Timedelta(days=-1)).strftime("%Y-%m-%d")
    end_date = row["Occurrence Date"].strftime("%Y-%m-%d")

    endpoint = "{}/timeline/{},{}/{}/{}".format(
        os.environ.get("WEATHER_URL"),
        row["Lat"],
        row["Long"],
        start_date,
        end_date
    )
    
    params = {
        "unitGroup": "metric",
        "key": os.environ.get("WEATHER_API_KEY")
    }
    
    response = requests.get(endpoint, params)
    result = json.loads(response.text)
    
    rain_yesterday.append(result["days"][0]["precip"])
    rain_today.append(result["days"][1]["precip"])
    
landslides_recent["Rain Yesterday"] = rain_yesterday
landslides_recent["Rain Today"] = rain_today

display(landslides_recent.describe())
landslides_recent

KeyboardInterrupt:

In [ ]:
landslides_recent.to_csv("../datasets/landslides_rainfall.csv", index = False, quoting = False)

In [18]:
landslides_recent = pd.read_csv("../Datasets/landslides_rainfall.csv")
landslides_recent["Occurrence Date"] = pd.to_datetime(landslides_recent["Occurrence Date"])

display(landslides_recent.describe())
landslides_recent

,Occurrence Date,Lat,Long,Confidence ratio (km),Deaths,Rain Yesterday,Rain Today
count,504,504.000000,504.000000,504.000000,504.000000,504.000000,504.000000
mean,2014-11-17 09:14:17.142857216,5.009067,-75.277083,9.658313,3.430556,8.609921,8.698810
min,2010-01-10 00:00:00,0.500000,-78.370000,0.100000,1.000000,0.000000,0.000000
25%,2011-09-19 18:00:00,3.132500,-76.145000,4.452500,1.000000,1.300000,1.600000
50%,2014-05-10 00:00:00,5.185000,-75.510000,7.850000,1.000000,5.100000,5.300000
75%,2017-12-05 12:00:00,6.440000,-74.325000,12.575000,3.000000,11.825000,11.600000
max,2020-12-25 00:00:00,11.250000,-68.010000,73.090000,333.000000,88.100000,89.100000
std,NaN,2.203510,1.414380,8.442951,16.055295,11.012548,10.544394

,Occurrence Date,Department,Municipality,Lat,Long,Confidence ratio (km),Deaths,Trigger,Source,Rain Yesterday,Rain Today
0,2010-01-10,BOGOTA,BOGOTA,4.63,-74.11,11.60,1,Unknown,HEB,0.0,0.0
1,2010-02-25,CUNDINAMARCA,VILLETA,5.01,-74.49,6.70,1,Rainfall,UNGRD,2.2,9.7
2,2010-04-10,TOLIMA,HERVEO,5.11,-75.19,1.52,1,Unknown,UNGRD,4.9,18.0
3,2010-04-10,VALLE DEL CAUCA,CALI,3.40,-76.58,13.44,1,Unknown,UNGRD,10.1,23.1
4,2010-04-29,BOGOTA,BOGOTA,4.63,-74.11,11.60,1,Unknown,UNGRD,4.4,16.3
...,...,...,...,...,...,...,...,...,...,...,...
499,2020-12-01,BOLIVAR,BARRANCO DE LOBA,8.84,-74.28,11.68,3,Human activity,News Report - UNGRD,0.0,0.0
500,2020-12-03,RISARALDA,PEREIRA,4.80,-75.80,13.91,1,Unknown,UNGRD,2.6,8.2
501,2020-12-12,ANTIOQUIA,SAN LUIS,6.00,-75.05,0.10,2,Unknown,News Report,0.0,0.0
502,2020-12-15,ANTIOQUIA,MEDELLIN,6.25,-75.58,6.50,2,Human activity,News Report,0.0,0.0
503,2020-12-25,ANTIOQUIA,ITAGUI,6.18,-75.61,2.53,2,Earthquake,News Report - UNGRD,0.0,0.0

In [14]:
random_sample = landslides_recent.sample(len(landslides_recent), replace = True, random_state = 1326)
random_sample

,Occurrence Date,Department,Municipality,Lat,Long,Confidence ratio (km),Deaths,Trigger,Source,Rain Yesterday,Rain Today
252,2014-05-11,HUILA,SUAZA,1.94,-75.80,1.24,1,Unknown,UNGRD,8.0,19.7
257,2014-09-09,CALDAS,MARMATO,5.49,-75.60,3.40,1,Human activity,ANM,0.0,0.0
69,2010-12-05,ANTIOQUIA,BELLO,6.36,-75.59,6.87,82,Rainfall,UNGRD,19.3,19.1
253,2014-05-26,TOLIMA,HERVEO,5.07,-75.24,10.14,1,Unknown,UNGRD,0.0,2.0
473,2020-03-14,SANTANDER,BUCARAMANGA,7.16,-73.11,6.99,1,Rainfall,UNGRD,8.2,11.6
...,...,...,...,...,...,...,...,...,...,...,...
474,2020-04-16,NARIÃ‘O,LA UNION (N),1.62,-77.14,6.73,1,Unknown,UNGRD,2.2,4.6
55,2010-11-22,CALDAS,PENSILVANIA,5.39,-75.11,0.76,5,Rainfall,UNGRD,3.1,4.9
472,2020-02-29,NARIÃ‘O,IPIALES,0.50,-77.24,22.45,1,Rainfall,UNGRD,4.9,0.3
18,2010-07-17,SANTANDER,BARICHARA,6.65,-73.21,6.62,2,Unknown,UNGRD,8.4,9.4
36,2010-11-07,BOYACA,OTANCHE,5.75,-74.20,12.30,6,Rainfall,DESINVENTAR,17.8,2.8

In [15]:
dates = []
first_date = datetime.strptime("2010-01-01", "%Y-%m-%d")

for i, row in random_sample.iterrows():
    time_delta = row["Occurrence Date"] - first_date
    random_delta = np.random.randint(0, time_delta.days)
    random_date = first_date + pd.Timedelta(days = random_delta)
    dates.append(random_date)
    
random_sample["Occurrence Date"] = dates
random_sample["Deaths"] = 0
random_sample["Trigger"] = "N/A"
random_sample.reset_index(drop = True, inplace = True)

random_sample

,Occurrence Date,Department,Municipality,Lat,Long,Confidence ratio (km),Deaths,Trigger,Source,Rain Yesterday,Rain Today
0,2011-03-03,HUILA,SUAZA,1.94,-75.80,1.24,0,N/A,UNGRD,8.0,19.7
1,2013-03-03,CALDAS,MARMATO,5.49,-75.60,3.40,0,N/A,ANM,0.0,0.0
2,2010-05-13,ANTIOQUIA,BELLO,6.36,-75.59,6.87,0,N/A,UNGRD,19.3,19.1
3,2013-01-28,TOLIMA,HERVEO,5.07,-75.24,10.14,0,N/A,UNGRD,0.0,2.0
4,2010-06-19,SANTANDER,BUCARAMANGA,7.16,-73.11,6.99,0,N/A,UNGRD,8.2,11.6
...,...,...,...,...,...,...,...,...,...,...,...
499,2012-02-09,NARIÃ‘O,LA UNION (N),1.62,-77.14,6.73,0,N/A,UNGRD,2.2,4.6
500,2010-06-18,CALDAS,PENSILVANIA,5.39,-75.11,0.76,0,N/A,UNGRD,3.1,4.9
501,2013-11-23,NARIÃ‘O,IPIALES,0.50,-77.24,22.45,0,N/A,UNGRD,4.9,0.3
502,2010-05-15,SANTANDER,BARICHARA,6.65,-73.21,6.62,0,N/A,UNGRD,8.4,9.4
503,2010-05-19,BOYACA,OTANCHE,5.75,-74.20,12.30,0,N/A,DESINVENTAR,17.8,2.8

In [16]:
rain_yesterday = []
rain_today = []

for i, row in random_sample.iterrows():
    start_date = (row["Occurrence Date"] + pd.Timedelta(days=-1)).strftime("%Y-%m-%d")
    end_date = row["Occurrence Date"].strftime("%Y-%m-%d")

    endpoint = "{}/timeline/{},{}/{}/{}".format(
        os.environ.get("WEATHER_URL"),
        row["Lat"],
        row["Long"],
        start_date,
        end_date
    )
    
    params = {
        "unitGroup": "metric",
        "key": os.environ.get("WEATHER_API_KEY")
    }
    
    response = requests.get(endpoint, params)
    result = json.loads(response.text)
    
    rain_yesterday.append(result["days"][0]["precip"])
    rain_today.append(result["days"][1]["precip"])
    
random_sample["Rain Yesterday"] = rain_yesterday
random_sample["Rain Today"] = rain_today

display(random_sample.describe())
random_sample

,Occurrence Date,Lat,Long,Confidence ratio (km),Deaths,Rain Yesterday,Rain Today
count,504,504.000000,504.000000,504.000000,504.0,504.000000,504.000000
mean,2012-05-16 21:45:42.857143040,4.966171,-75.221706,9.305377,0.0,5.319643,4.932540
min,2010-01-01 00:00:00,0.500000,-78.370000,0.100000,0.0,0.000000,0.000000
25%,2010-06-26 00:00:00,3.097500,-76.010000,4.655000,0.0,0.100000,0.000000
50%,2011-05-30 00:00:00,5.120000,-75.490000,7.870000,0.0,2.200000,2.100000
75%,2013-10-06 12:00:00,6.502500,-74.270000,12.410000,0.0,6.500000,7.025000
max,2019-09-11 00:00:00,11.120000,-68.010000,73.090000,0.0,112.000000,53.400000
std,NaN,2.193032,1.407167,7.874268,0.0,8.971585,7.223408

,Occurrence Date,Department,Municipality,Lat,Long,Confidence ratio (km),Deaths,Trigger,Source,Rain Yesterday,Rain Today
0,2011-03-03,HUILA,SUAZA,1.94,-75.80,1.24,0,N/A,UNGRD,9.5,0.2
1,2013-03-03,CALDAS,MARMATO,5.49,-75.60,3.40,0,N/A,ANM,0.0,0.9
2,2010-05-13,ANTIOQUIA,BELLO,6.36,-75.59,6.87,0,N/A,UNGRD,0.2,0.4
3,2013-01-28,TOLIMA,HERVEO,5.07,-75.24,10.14,0,N/A,UNGRD,0.0,0.0
4,2010-06-19,SANTANDER,BUCARAMANGA,7.16,-73.11,6.99,0,N/A,UNGRD,24.5,12.7
...,...,...,...,...,...,...,...,...,...,...,...
499,2012-02-09,NARIÃ‘O,LA UNION (N),1.62,-77.14,6.73,0,N/A,UNGRD,19.7,0.0
500,2010-06-18,CALDAS,PENSILVANIA,5.39,-75.11,0.76,0,N/A,UNGRD,1.6,11.0
501,2013-11-23,NARIÃ‘O,IPIALES,0.50,-77.24,22.45,0,N/A,UNGRD,1.6,2.1
502,2010-05-15,SANTANDER,BARICHARA,6.65,-73.21,6.62,0,N/A,UNGRD,0.1,3.7
503,2010-05-19,BOYACA,OTANCHE,5.75,-74.20,12.30,0,N/A,DESINVENTAR,5.5,9.0

In [20]:
landslides_recent["Landslide"] = 1
random_sample["Landslide"] = 0

df_final = pd.concat([landslides_recent, random_sample]).reset_index(drop = True)

display(df_final.groupby("Landslide")[["Rain Yesterday", "Rain Today"]].describe())
df_final

          Rain Yesterday                                                     \
                   count      mean        std  min  25%  50%     75%    max
Landslide
0                  504.0  5.319643   8.971585  0.0  0.1  2.2   6.500  112.0
1                  504.0  8.609921  11.012548  0.0  1.3  5.1  11.825   88.1

          Rain Today
               count     mean        std  min  25%  50%     75%   max
Landslide
0              504.0  4.93254   7.223408  0.0  0.0  2.1   7.025  53.4
1              504.0  8.69881  10.544394  0.0  1.6  5.3  11.600  89.1

,Occurrence Date,Department,Municipality,Lat,Long,Confidence ratio (km),Deaths,Trigger,Source,Rain Yesterday,Rain Today,Landslide
0,2010-01-10,BOGOTA,BOGOTA,4.63,-74.11,11.60,1,Unknown,HEB,0.0,0.0,1
1,2010-02-25,CUNDINAMARCA,VILLETA,5.01,-74.49,6.70,1,Rainfall,UNGRD,2.2,9.7,1
2,2010-04-10,TOLIMA,HERVEO,5.11,-75.19,1.52,1,Unknown,UNGRD,4.9,18.0,1
3,2010-04-10,VALLE DEL CAUCA,CALI,3.40,-76.58,13.44,1,Unknown,UNGRD,10.1,23.1,1
4,2010-04-29,BOGOTA,BOGOTA,4.63,-74.11,11.60,1,Unknown,UNGRD,4.4,16.3,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1003,2012-02-09,NARIÃ‘O,LA UNION (N),1.62,-77.14,6.73,0,N/A,UNGRD,19.7,0.0,0
1004,2010-06-18,CALDAS,PENSILVANIA,5.39,-75.11,0.76,0,N/A,UNGRD,1.6,11.0,0
1005,2013-11-23,NARIÃ‘O,IPIALES,0.50,-77.24,22.45,0,N/A,UNGRD,1.6,2.1,0
1006,2010-05-15,SANTANDER,BARICHARA,6.65,-73.21,6.62,0,N/A,UNGRD,0.1,3.7,0
1007,2010-05-19,BOYACA,OTANCHE,5.75,-74.20,12.30,0,N/A,DESINVENTAR,5.5,9.0,0

In [21]:
df_final.to_csv("../datasets/rainfall.csv", index = False, quoting = False)